"""Inline keyboards and their callback payloads."""

from gym_assistant.bot.keyboards.exercises import (
    EQUIPMENT_BY_VALUE,
    TYPE_BY_VALUE,
    ExCardCB,
    ExFavCB,
    ExGroupCB,
    ExHideCB,
    ExMenuCB,
    ExNewCB,
    ExUnhideCB,
    exercise_card_keyboard,
    exercise_list_keyboard,
    groups_keyboard,
    menu_keyboard,
    new_equipment_keyboard,
    new_group_keyboard,
    new_type_keyboard,
    search_results_keyboard,
    undo_hide_keyboard,
)
from gym_assistant.bot.keyboards.main_menu import MainMenuCB, main_menu_keyboard
from gym_assistant.bot.keyboards.profile import (
    CHOICE_ENUMS,
    ChoiceCB,
    EditCB,
    SkipCB,
    experience_keyboard,
    goal_keyboard,
    profile_keyboard,
    sex_keyboard,
    skip_keyboard,
)

__all__ = [
    "CHOICE_ENUMS",
    "EQUIPMENT_BY_VALUE",
    "TYPE_BY_VALUE",
    "ChoiceCB",
    "EditCB",
    "ExCardCB",
    "ExFavCB",
    "ExGroupCB",
    "ExHideCB",
    "ExMenuCB",
    "ExNewCB",
    "ExUnhideCB",
    "MainMenuCB",
    "SkipCB",
    "exercise_card_keyboard",
    "exercise_list_keyboard",
    "experience_keyboard",
    "goal_keyboard",
    "groups_keyboard",
    "main_menu_keyboard",
    "menu_keyboard",
    "new_equipment_keyboard",
    "new_group_keyboard",
    "new_type_keyboard",
    "profile_keyboard",
    "search_results_keyboard",
    "sex_keyboard",
    "skip_keyboard",
    "undo_hide_keyboard",
]
