"""Inline keyboards and their callback payloads."""

from gym_assistant.bot.keyboards.common import CancelCB, cancel_button, cancel_keyboard, with_cancel
from gym_assistant.bot.keyboards.exercises import (
    EQUIPMENT_BY_VALUE,
    TYPE_BY_VALUE,
    ExCardCB,
    ExFavCB,
    ExHideCB,
    ExListCB,
    ExMenuCB,
    ExNewCB,
    ExUnhideCB,
    exercise_card_keyboard,
    exercise_list_keyboard,
    groups_keyboard,
    menu_keyboard,
    new_equipment_keyboard,
    new_group_keyboard,
    new_type_keyboard,
    undo_hide_keyboard,
)
from gym_assistant.bot.keyboards.main_menu import MainMenuCB, main_menu_keyboard
from gym_assistant.bot.keyboards.profile import (
    CHOICE_ENUMS,
    ChoiceCB,
    EditCB,
    SkipCB,
    experience_keyboard,
    goal_keyboard,
    profile_keyboard,
    sex_keyboard,
    skip_keyboard,
)
from gym_assistant.bot.keyboards.workouts import (
    SetAdjustCB,
    SetCommitCB,
    WorkoutCB,
    WorkoutExerciseCB,
    back_to_panel_keyboard,
    panel_keyboard,
    set_entry_keyboard,
    start_keyboard,
)

__all__ = [
    "CHOICE_ENUMS",
    "EQUIPMENT_BY_VALUE",
    "TYPE_BY_VALUE",
    "CancelCB",
    "ChoiceCB",
    "EditCB",
    "ExCardCB",
    "ExFavCB",
    "ExHideCB",
    "ExListCB",
    "ExMenuCB",
    "ExNewCB",
    "ExUnhideCB",
    "MainMenuCB",
    "SetAdjustCB",
    "SetCommitCB",
    "SkipCB",
    "WorkoutCB",
    "WorkoutExerciseCB",
    "back_to_panel_keyboard",
    "cancel_button",
    "cancel_keyboard",
    "exercise_card_keyboard",
    "exercise_list_keyboard",
    "experience_keyboard",
    "goal_keyboard",
    "groups_keyboard",
    "main_menu_keyboard",
    "menu_keyboard",
    "new_equipment_keyboard",
    "new_group_keyboard",
    "new_type_keyboard",
    "panel_keyboard",
    "profile_keyboard",
    "set_entry_keyboard",
    "sex_keyboard",
    "skip_keyboard",
    "start_keyboard",
    "undo_hide_keyboard",
    "with_cancel",
]
